### ISSUE TITLE
Problems after 4.0 update

### ISSUE THREAD

**Issue by TTsdzb** [yojohanshinwataikei/vscode-arcaea-file-format#2]
After the 4.0.0 update there are following problems:
+ lowiro added scenecontrol events named "enwidencamera" and "enwidenlanes" which causes 6 lanes and wider trapezium range.  
+ The value in the "track-id" field of event with type "hold" now can be 0 or 5 after enwiden.  
+ There is a special arc tap called "kick_wav".

**Comment by yojohanshinwataikei** [comment]
Fixed
