### ISSUE TITLE
vscode for arcaea file format "plist" - particle and combo note color typescript

### ISSUE THREAD

**Issue by Hajimayamiro** [yojohanshinwataikei/vscode-arcaea-file-format#4]
Can you create a typescript for reading and editing plist and combo note color, thank you @yojohanshinwataikei

**Comment by yojohanshinwataikei** [comment]
They are standrad cocos2dx particle file, use http://www.effecthub.com/particle2dx to edit it.

**Comment by Hajimayamiro** [comment]
sadly i don't have a pc to edit it
